name: build
on: 
  pull_request:
    branches: [main]
    paths:
      - "**.go"
      - "**.yaml"
      - "**.mod"
      - "**.sum"
      - "!capm.yaml"
      - "!osc-secret.yaml"
      - "!example/**.yaml"
      - "!helm/**"
      - "Makefile"
      - "!docs/src/**"
      - "!hack/json-format/*.sh"
      - "!hack/json-format/src/*.rs"
      - "!hack/json-format/Makefile"
      - "!hack/json-format/Cargo.*"
      - "!hack/json-format/tests/*.rs"
  push:
    branches:
      - 'main'
    paths:
      - "**.go"
      - "**.yaml"
      - "!capm.yaml"
      - "!osc-secret.yaml"
      - "!example/**.yaml"
      - "!helm/**"
      - "Makefile"
      - "!docs/src/**"
      - "!hack/json-format/*.sh"
      - "!hack/json-format/src/*.rs"
      - "!hack/json-format/Makefile"
      - "!hack/json-format/Cargo.*"
      - "!hack/json-format/tests/*.rs"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
	  go-version-file: './go.mod'
      - name: check-gofmt
        run: make checkfmt
        shell: bash
      - name: Check with boilerplate
        run: make verify-boilerplate
        shell: bash
      - name: check with ShellCheck
        run: make install-shellcheck
        shell: bash
      - name: Install yamllint
        run: pip install yamllint
      - name: check with yamlint
        run: yamllint -c .github/linters/yaml-lint.yaml . --format github
      - name: Run make build
        run: make build
        shell: bash
